// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXW7_d3xSv6g0Pbj3O_WxDHj_97ynTvnA',
    appId: '1:362944004167:web:fead1a4d08f24bf457b162',
    messagingSenderId: '362944004167',
    projectId: 'count20',
    authDomain: 'count20.firebaseapp.com',
    databaseURL: 'https://count20-default-rtdb.firebaseio.com',
    storageBucket: 'count20.appspot.com',
    measurementId: 'G-QBM1QD53VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51wC5ukaaE7aHIq6RfbDWguIMrOmlVqw',
    appId: '1:362944004167:android:0953047e6db29fd957b162',
    messagingSenderId: '362944004167',
    projectId: 'count20',
    databaseURL: 'https://count20-default-rtdb.firebaseio.com',
    storageBucket: 'count20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBopqtR5vDyqMqdW-4cBKqukU_9W6Y3FrY',
    appId: '1:362944004167:ios:c2eda996b944d41757b162',
    messagingSenderId: '362944004167',
    projectId: 'count20',
    databaseURL: 'https://count20-default-rtdb.firebaseio.com',
    storageBucket: 'count20.appspot.com',
    iosBundleId: 'com.example.facebookCloneInFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBopqtR5vDyqMqdW-4cBKqukU_9W6Y3FrY',
    appId: '1:362944004167:ios:c2eda996b944d41757b162',
    messagingSenderId: '362944004167',
    projectId: 'count20',
    databaseURL: 'https://count20-default-rtdb.firebaseio.com',
    storageBucket: 'count20.appspot.com',
    iosBundleId: 'com.example.facebookCloneInFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXW7_d3xSv6g0Pbj3O_WxDHj_97ynTvnA',
    appId: '1:362944004167:web:324f7e02606de6a957b162',
    messagingSenderId: '362944004167',
    projectId: 'count20',
    authDomain: 'count20.firebaseapp.com',
    databaseURL: 'https://count20-default-rtdb.firebaseio.com',
    storageBucket: 'count20.appspot.com',
    measurementId: 'G-89DCSQP22X',
  );
}
